// districts.js
export const districtOfGhana = [
  // AHAFO (6 districts)
  { name: "Asunafo North", region: "AHAFO" },
  { name: "Asunafo South", region: "AHAFO" },
  { name: "Asutifi North", region: "AHAFO" },
  { name: "Asutifi South", region: "AHAFO" },
  { name: "Tano North", region: "AHAFO" },
  { name: "Tano South", region: "AHAFO" },

  // ASHANTI (43 districts)
  { name: "Adansi North", region: "ASHANTI" },
  { name: "Adansi South", region: "ASHANTI" },
  { name: "Afigya Kwabre North", region: "ASHANTI" },
  { name: "Afigya Kwabre South", region: "ASHANTI" },
  { name: "Ahafo Ano North", region: "ASHANTI" },
  { name: "Ahafo Ano South East", region: "ASHANTI" },
  { name: "Ahafo Ano South West", region: "ASHANTI" },
  { name: "Amansie Central", region: "ASHANTI" },
  { name: "Amansie South", region: "ASHANTI" },
  { name: "Amansie West", region: "ASHANTI" },
  { name: "Asante Akim Central", region: "ASHANTI" },
  { name: "Asante Akim North", region: "ASHANTI" },
  { name: "Asante Akim South", region: "ASHANTI" },
  { name: "Asokore Mampong", region: "ASHANTI" },
  { name: "Asokwa", region: "ASHANTI" },
  { name: "Atwima Kwanwoma", region: "ASHANTI" },
  { name: "Atwima Mponua", region: "ASHANTI" },
  { name: "Atwima Nwabiagya North", region: "ASHANTI" },
  { name: "Atwima Nwabiagya South", region: "ASHANTI" },
  { name: "Bekwai", region: "ASHANTI" },
  { name: "Bosome Freho", region: "ASHANTI" },
  { name: "Bosomtwe", region: "ASHANTI" },
  { name: "Ejisu", region: "ASHANTI" },
  { name: "Ejura Sekyedumase", region: "ASHANTI" },
  { name: "Juaben", region: "ASHANTI" },
  { name: "Kumasi Metropolitan", region: "ASHANTI" },
  { name: "Kwabre East", region: "ASHANTI" },
  { name: "Kwadaso", region: "ASHANTI" },
  { name: "Mampong", region: "ASHANTI" },
  { name: "Obuasi East", region: "ASHANTI" },
  { name: "Obuasi Municipal", region: "ASHANTI" },
  { name: "Offinso North", region: "ASHANTI" },
  { name: "Offinso South", region: "ASHANTI" },
  { name: "Oforikrom", region: "ASHANTI" },
  { name: "Old Tafo", region: "ASHANTI" },
  { name: "Sekyere Afram Plains", region: "ASHANTI" },
  { name: "Sekyere Central", region: "ASHANTI" },
  { name: "Sekyere East", region: "ASHANTI" },
  { name: "Sekyere Kumawu", region: "ASHANTI" },
  { name: "Sekyere South", region: "ASHANTI" },
  { name: "Suame", region: "ASHANTI" },
  { name: "Tafo", region: "ASHANTI" },

  // BONO (12 districts)
  { name: "Banda", region: "BONO" },
  { name: "Berekum East", region: "BONO" },
  { name: "Berekum West", region: "BONO" },
  { name: "Dormaa Central", region: "BONO" },
  { name: "Dormaa East", region: "BONO" },
  { name: "Dormaa West", region: "BONO" },
  { name: "Jaman North", region: "BONO" },
  { name: "Jaman South", region: "BONO" },
  { name: "Sunyani East", region: "BONO" },
  { name: "Sunyani West", region: "BONO" },
  { name: "Tain", region: "BONO" },
  { name: "Wenchi", region: "BONO" },

  // BONO EAST (11 districts)
  { name: "Atebubu-Amantin", region: "BONO EAST" },
  { name: "Kintampo North", region: "BONO EAST" },
  { name: "Kintampo South", region: "BONO EAST" },
  { name: "Nkoranza North", region: "BONO EAST" },
  { name: "Nkoranza South", region: "BONO EAST" },
  { name: "Pru East", region: "BONO EAST" },
  { name: "Pru West", region: "BONO EAST" },
  { name: "Sene East", region: "BONO EAST" },
  { name: "Sene West", region: "BONO EAST" },
  { name: "Techiman North", region: "BONO EAST" },
  { name: "Techiman South", region: "BONO EAST" },

  // CENTRAL (22 districts)
  { name: "Abura Asebu Kwamankese", region: "CENTRAL" },
  { name: "Agona East", region: "CENTRAL" },
  { name: "Agona West", region: "CENTRAL" },
  { name: "Ajumako Enyan Essiam", region: "CENTRAL" },
  { name: "Asikuma Odoben Brakwa", region: "CENTRAL" },
  { name: "Assin Central", region: "CENTRAL" },
  { name: "Assin North", region: "CENTRAL" },
  { name: "Assin South", region: "CENTRAL" },
  { name: "Awutu Senya East", region: "CENTRAL" },
  { name: "Awutu Senya West", region: "CENTRAL" },
  { name: "Cape Coast Metropolitan", region: "CENTRAL" },
  { name: "Effutu", region: "CENTRAL" },
  { name: "Ekumfi", region: "CENTRAL" },
  { name: "Gomoa Central", region: "CENTRAL" },
  { name: "Gomoa East", region: "CENTRAL" },
  { name: "Gomoa West", region: "CENTRAL" },
  { name: "Hemang Lower Denkyira", region: "CENTRAL" },
  { name: "Komenda Edina Eguafo Abirem", region: "CENTRAL" },
  { name: "Mfantseman", region: "CENTRAL" },
  { name: "Twifo Atti Morkwa", region: "CENTRAL" },
  { name: "Upper Denkyira East", region: "CENTRAL" },
  { name: "Upper Denkyira West", region: "CENTRAL" },

  // EASTERN (33 districts)
  { name: "Abuakwa North", region: "EASTERN" },
  { name: "Abuakwa South", region: "EASTERN" },
  { name: "Achiase", region: "EASTERN" },
  { name: "Akwapim North", region: "EASTERN" },
  { name: "Akwapim South", region: "EASTERN" },
  { name: "Akyemansa", region: "EASTERN" },
  { name: "Asene Manso Akroso", region: "EASTERN" },
  { name: "Asuogyaman", region: "EASTERN" },
  { name: "Atiwa East", region: "EASTERN" },
  { name: "Atiwa West", region: "EASTERN" },
  { name: "Ayensuano", region: "EASTERN" },
  { name: "Birim Central", region: "EASTERN" },
  { name: "Birim North", region: "EASTERN" },
  { name: "Birim South", region: "EASTERN" },
  { name: "Denkyembour", region: "EASTERN" },
  { name: "Fanteakwa North", region: "EASTERN" },
  { name: "Fanteakwa South", region: "EASTERN" },
  { name: "Kwaebibirem", region: "EASTERN" },
  { name: "Kwahu Afram Plains North", region: "EASTERN" },
  { name: "Kwahu Afram Plains South", region: "EASTERN" },
  { name: "Kwahu East", region: "EASTERN" },
  { name: "Kwahu South", region: "EASTERN" },
  { name: "Kwahu West", region: "EASTERN" },
  { name: "Lower Manya Krobo", region: "EASTERN" },
  { name: "New Juaben North", region: "EASTERN" },
  { name: "New Juaben South", region: "EASTERN" },
  { name: "Nsawam Adoagyiri", region: "EASTERN" },
  { name: "Okere", region: "EASTERN" },
  { name: "Suhum", region: "EASTERN" },
  { name: "Upper Manya Krobo", region: "EASTERN" },
  { name: "Upper West Akim", region: "EASTERN" },
  { name: "West Akim", region: "EASTERN" },
  { name: "Yilo Krobo", region: "EASTERN" },

  // GREATER ACCRA (29 districts)
  { name: "Ablekuma Central", region: "GREATER ACCRA" },
  { name: "Ablekuma North", region: "GREATER ACCRA" },
  { name: "Ablekuma West", region: "GREATER ACCRA" },
  { name: "Accra Metropolitan", region: "GREATER ACCRA" },
  { name: "Ada East", region: "GREATER ACCRA" },
  { name: "Ada West", region: "GREATER ACCRA" },
  { name: "Adenta", region: "GREATER ACCRA" },
  { name: "Ashaiman", region: "GREATER ACCRA" },
  { name: "Ayawaso Central", region: "GREATER ACCRA" },
  { name: "Ayawaso East", region: "GREATER ACCRA" },
  { name: "Ayawaso North", region: "GREATER ACCRA" },
  { name: "Ayawaso West", region: "GREATER ACCRA" },
  { name: "Ga Central", region: "GREATER ACCRA" },
  { name: "Ga East", region: "GREATER ACCRA" },
  { name: "Ga North", region: "GREATER ACCRA" },
  { name: "Ga South", region: "GREATER ACCRA" },
  { name: "Ga West", region: "GREATER ACCRA" },
  { name: "Kpone Katamanso", region: "GREATER ACCRA" },
  { name: "Krowor", region: "GREATER ACCRA" },
  { name: "La Dade Kotopon", region: "GREATER ACCRA" },
  { name: "La Nkwantanang Madina", region: "GREATER ACCRA" },
  { name: "Ledzokuku", region: "GREATER ACCRA" },
  { name: "Ningo Prampram", region: "GREATER ACCRA" },
  { name: "Okaikwei North", region: "GREATER ACCRA" },
  { name: "Shai Osudoku", region: "GREATER ACCRA" },
  { name: "Tema East", region: "GREATER ACCRA" },
  { name: "Tema Metropolitan", region: "GREATER ACCRA" },
  { name: "Tema West", region: "GREATER ACCRA" },
  { name: "Weija Gbawe", region: "GREATER ACCRA" },

  // NORTH EAST (6 districts)
  { name: "Bunkpurugu Nyankpanduri", region: "NORTH EAST" },
  { name: "Chereponi", region: "NORTH EAST" },
  { name: "East Mamprusi", region: "NORTH EAST" },
  { name: "Mamprugu Moagduri", region: "NORTH EAST" },
  { name: "West Mamprusi", region: "NORTH EAST" },
  { name: "Yunyoo Nasuan", region: "NORTH EAST" },

  // NORTHERN (16 districts)
  { name: "Gusheigu", region: "NORTHERN" },
  { name: "Karaga", region: "NORTHERN" },
  { name: "Kpandai", region: "NORTHERN" },
  { name: "Kumbungu", region: "NORTHERN" },
  { name: "Mion", region: "NORTHERN" },
  { name: "Nanton", region: "NORTHERN" },
  { name: "Nanumba North", region: "NORTHERN" },
  { name: "Nanumba South", region: "NORTHERN" },
  { name: "Saboba", region: "NORTHERN" },
  { name: "Sagnarigu", region: "NORTHERN" },
  { name: "Savelugu", region: "NORTHERN" },
  { name: "Tamale Metropolitan", region: "NORTHERN" },
  { name: "Tatale Sanguli", region: "NORTHERN" },
  { name: "Tolon", region: "NORTHERN" },
  { name: "Yendi", region: "NORTHERN" },
  { name: "Zabzugu", region: "NORTHERN" },

  // OTI (9 districts)
  { name: "Biakoye", region: "OTI" },
  { name: "Guan", region: "OTI" },
  { name: "Jasikan", region: "OTI" },
  { name: "Kadjebi", region: "OTI" },
  { name: "Krachi East", region: "OTI" },
  { name: "Krachi Nchumuru", region: "OTI" },
  { name: "Krachi West", region: "OTI" },
  { name: "Nkwanta North", region: "OTI" },
  { name: "Nkwanta South", region: "OTI" },

  // SAVANNAH (7 districts)
  { name: "Bole", region: "SAVANNAH" },
  { name: "Central Gonja", region: "SAVANNAH" },
  { name: "East Gonja", region: "SAVANNAH" },
  { name: "North East Gonja", region: "SAVANNAH" },
  { name: "North Gonja", region: "SAVANNAH" },
  { name: "Sawla Tuna Kalba", region: "SAVANNAH" },
  { name: "West Gonja", region: "SAVANNAH" },

  // UPPER EAST (15 districts)
  { name: "Bawku Municipal", region: "UPPER EAST" },
  { name: "Bawku West", region: "UPPER EAST" },
  { name: "Binduri", region: "UPPER EAST" },
  { name: "Bolgatanga East", region: "UPPER EAST" },
  { name: "Bolgatanga Municipal", region: "UPPER EAST" },
  { name: "Bongo", region: "UPPER EAST" },
  { name: "Builsa North", region: "UPPER EAST" },
  { name: "Builsa South", region: "UPPER EAST" },
  { name: "Garu", region: "UPPER EAST" },
  { name: "Kassena Nankana East", region: "UPPER EAST" },
  { name: "Kassena Nankana West", region: "UPPER EAST" },
  { name: "Nabdam", region: "UPPER EAST" },
  { name: "Pusiga", region: "UPPER EAST" },
  { name: "Talensi", region: "UPPER EAST" },
  { name: "Tempane", region: "UPPER EAST" },

  // UPPER WEST (11 districts)
  { name: "Daffiama Bussie Issa", region: "UPPER WEST" },
  { name: "Jirapa", region: "UPPER WEST" },
  { name: "Lambussie Karni", region: "UPPER WEST" },
  { name: "Lawra", region: "UPPER WEST" },
  { name: "Nadowli Kaleo", region: "UPPER WEST" },
  { name: "Nandom", region: "UPPER WEST" },
  { name: "Sissala East", region: "UPPER WEST" },
  { name: "Sissala West", region: "UPPER WEST" },
  { name: "Wa East", region: "UPPER WEST" },
  { name: "Wa Municipal", region: "UPPER WEST" },
  { name: "Wa West", region: "UPPER WEST" },

  // VOLTA (18 districts)
  { name: "Adaklu", region: "VOLTA" },
  { name: "Afadzato South", region: "VOLTA" },
  { name: "Agotime Ziope", region: "VOLTA" },
  { name: "Akatsi North", region: "VOLTA" },
  { name: "Akatsi South", region: "VOLTA" },
  { name: "Anloga", region: "VOLTA" },
  { name: "Central Tongu", region: "VOLTA" },
  { name: "Ho Municipal", region: "VOLTA" },
  { name: "Ho West", region: "VOLTA" },
  { name: "Hohoe", region: "VOLTA" },
  { name: "Keta", region: "VOLTA" },
  { name: "Ketu North", region: "VOLTA" },
  { name: "Ketu South", region: "VOLTA" },
  { name: "Kpando", region: "VOLTA" },
  { name: "North Dayi", region: "VOLTA" },
  { name: "North Tongu", region: "VOLTA" },
  { name: "South Dayi", region: "VOLTA" },
  { name: "South Tongu", region: "VOLTA" },

  // WESTERN (14 districts)
  { name: "Ahanta West", region: "WESTERN" },
  { name: "Amenfi Central", region: "WESTERN" },
  { name: "Amenfi East", region: "WESTERN" },
  { name: "Amenfi West", region: "WESTERN" },
  { name: "Effia", region: "WESTERN" },
  { name: "Ellembelle", region: "WESTERN" },
  { name: "Essikado-Ketan", region: "WESTERN" },
  { name: "Jomoro", region: "WESTERN" },
  { name: "Kwesimintsim", region: "WESTERN" },
  { name: "Mpohor", region: "WESTERN" },
  { name: "Nzema East", region: "WESTERN" },
  { name: "Prestea-Huni Valley", region: "WESTERN" },
  { name: "Sekondi Takoradi Metropolitan", region: "WESTERN" },
  { name: "Tarkwa Nsuaem", region: "WESTERN" },

  // WESTERN NORTH (9 districts)
  { name: "Aowin", region: "WESTERN NORTH" },
  { name: "Bia East", region: "WESTERN NORTH" },
  { name: "Bia West", region: "WESTERN NORTH" },
  { name: "Bibiani Anhwiaso Bekwai", region: "WESTERN NORTH" },
  { name: "Bodi", region: "WESTERN NORTH" },
  { name: "Juaboso", region: "WESTERN NORTH" },
  { name: "Sefwi Akontombra", region: "WESTERN NORTH" },
  { name: "Sefwi Wiawso", region: "WESTERN NORTH" },
  { name: "Suaman", region: "WESTERN NORTH" },
];
