export const districtOfGhana = [
  { name: "All-districts", region: "Ashanti" },
  { name: "Bunkpurugu-Nakpanduri", region: "Northern" },
  { name: "Central Gonja", region: "Northern" },
  { name: "Chereponi", region: "Northern" },
  { name: "East Gonja", region: "Northern" },
  { name: "Gushiegu", region: "Northern" },
  { name: "Karaga", region: "Northern" },
  { name: "Kpandai", region: "Northern" },
  { name: "Mion", region: "Northern" },
  { name: "Nantom", region: "Northern" },
  { name: "Nanumba North", region: "Northern" },
  { name: "Nanumba South", region: "Northern" },
  { name: "Saboba", region: "Northern" },
  { name: "Sagnerigu", region: "Northern" },
  { name: "Savelugu Municipal", region: "Northern" },
  { name: "Tamale", region: "Northern" },
  { name: "Tatale Sangui", region: "Northern" },
  { name: "Tolon", region: "Northern" },
  { name: "Yendi", region: "Northern" },
  { name: "Zabzugu", region: "Northern" },
  { name: "Bunkpurugu Nakpanduri", region: "North East" },
  { name: "Chereponi", region: "North East" },
  { name: "East Mamprusi", region: "North East" },
  { name: "Mamprugu-Moaduri", region: "North East" },
  { name: "Nalerigu/Gambaga", region: "North East" },
  { name: "Nassana", region: "North East" },
  { name: "Talensi", region: "North East" },
  { name: "Bole", region: "Savannah" },
  { name: "Central Gonja", region: "Savannah" },
  { name: "East Gonja", region: "Savannah" },
  { name: "North East Gonja", region: "Savannah" },
  { name: "Sawla-Tuna-Kalba", region: "Savannah" },
  { name: "North Gonja", region: "Savannah" },
  { name: "West Gonja", region: "Savannah" },
  { name: "Daffiama-Bussie-Issa", region: "Upper West" },
  { name: "Nandom", region: "Upper West" },
  { name: "Jirapa", region: "Upper West" },
  { name: "Lambussie-Karni", region: "Upper West" },
  { name: "Lawra", region: "Upper West" },
  { name: "Nadowli-Kaleo", region: "Upper West" },
  { name: "Sissala East", region: "Upper West" },
  { name: "Sissala West", region: "Upper West" },
  { name: "Wa Municipal", region: "Upper West" },
  { name: "Wa East", region: "Upper West" },
  { name: "Wa West", region: "Upper West" },
  { name: "Bawku Municipal", region: "Upper East" },
  { name: "Bawku West", region: "Upper East" },
  { name: "Bolgatanga Municipal", region: "Upper East" },
  { name: "Bongo", region: "Upper East" },
  { name: "Kassena-Nankana East", region: "Upper East" },
  { name: "Kassena-Nankana West", region: "Upper East" },
  { name: "Nabdam", region: "Upper East" },
  { name: "Pusiga", region: "Upper East" },
  { name: "Talensi", region: "Upper East" },
  { name: "Bolga East", region: "Upper East" },
  { name: "Builsa North", region: "Upper East" },
  { name: "Builsa South", region: "Upper East" },
  { name: "Garu", region: "Upper East" },
  { name: "Tempane", region: "Upper East" },
  { name: "Asunafo North", region: "Ahafo" },
  { name: "Asunafo South", region: "Ahafo" },
  { name: "Asutifi North", region: "Ahafo" },
  { name: "Asutifi South", region: "Ahafo" },
  { name: "Tano North", region: "Ahafo" },
  { name: "Tano South", region: "Ahafo" },
  { name: "Adansi Akrofuom", region: "Ashanti" },
  { name: "Adansi Asokwa", region: "Ashanti" },
  { name: "Adansi South", region: "Ashanti" },
  { name: "Afigya-Kwabre North", region: "Ashanti" },
  { name: "Afigya-Kwabre South", region: "Ashanti" },
  { name: "Ahafo-Ano North", region: "Ashanti" },
  { name: "Ahafo-Ano South East", region: "Ashanti" },
  { name: "Ahafo-Ano South West", region: "Ashanti" },
  { name: "Amansie Central", region: "Ashanti" },
  { name: "Amansie South", region: "Ashanti" },
  { name: "Amansie West", region: "Ashanti" },
  { name: "Asante-Akim Central", region: "Ashanti" },
  { name: "Asante-Akim North", region: "Ashanti" },
  { name: "Asante-Akim South", region: "Ashanti" },
  { name: "Asokore-Mampong", region: "Ashanti" },
  { name: "Asokwa", region: "Ashanti" },
  { name: "Atwima-Kwanwoma", region: "Ashanti" },
  { name: "Atwima-Mponua", region: "Ashanti" },
  { name: "Atwima-Nwabiagya North", region: "Ashanti" },
  { name: "Atwima-Nwabiagya South", region: "Ashanti" },
  { name: "Bekwai", region: "Ashanti" },
  { name: "Bosome Freho", region: "Ashanti" },
  { name: "Bosomtwe", region: "Ashanti" },
  { name: "Ejisu", region: "Ashanti" },
  { name: "Ejura-Sekyedumasi", region: "Ashanti" },
  { name: "Juaben", region: "Ashanti" },
  { name: "Kumasi", region: "Ashanti" },
  { name: "Kwabre East", region: "Ashanti" },
  { name: "Kwadaso", region: "Ashanti" },
  { name: "Mampong", region: "Ashanti" },
  { name: "Obuasi East", region: "Ashanti" },
  { name: "Obuasi", region: "Ashanti" },
  { name: "Offinso North", region: "Ashanti" },
  { name: "Offinso", region: "Ashanti" },
  { name: "Oforikrom", region: "Ashanti" },
  { name: "Old Tafo", region: "Ashanti" },
  { name: "Sekyere Afram Plains", region: "Ashanti" },
  { name: "Sekyere Central", region: "Ashanti" },
  { name: "Sekyere East", region: "Ashanti" },
  { name: "Sekyere Kumawu", region: "Ashanti" },
  { name: "Sekyere South", region: "Ashanti" },
  { name: "Suame", region: "Ashanti" },
  { name: "Atebubu-Amantin", region: "Bono East" },
  { name: "Kintampo North", region: "Bono East" },
  { name: "Kintampo South", region: "Bono East" },
  { name: "Nkoranza North", region: "Bono East" },
  { name: "Nkoranza South", region: "Bono East" },
  { name: "Pru East", region: "Bono East" },
  { name: "Pru West", region: "Bono East" },
  { name: "Sene East", region: "Bono East" },
  { name: "Sene West", region: "Bono East" },
  { name: "Techiman North", region: "Bono East" },
  { name: "Techiman", region: "Bono East" },
  { name: "Banda", region: "Bono" },
  { name: "Berekum East", region: "Bono" },
  { name: "Berekum West", region: "Bono" },
  { name: "Dormaa East", region: "Bono" },
  { name: "Dormaa West", region: "Bono" },
  { name: "Dormaa", region: "Bono" },
  { name: "Jaman North", region: "Bono" },
  { name: "Jaman South", region: "Bono" },
  { name: "Sunyani West", region: "Bono" },
  { name: "Sunyani", region: "Bono" },
  { name: "Tain", region: "Bono" },
  { name: "Wenchi", region: "Bono" },
  { name: "Abura-Asebu-Kwamankese", region: "Central" },
  { name: "Agona East", region: "Central" },
  { name: "Agona West", region: "Central" },
  { name: "Ajumako-Enyan-Essiam", region: "Central" },
  { name: "Asikuma-Odoben-Brakwa", region: "Central" },
  { name: "Assin Central", region: "Central" },
  { name: "Assin North", region: "Central" },
  { name: "Assin South", region: "Central" },
  { name: "Awutu Senya East", region: "Central" },
  { name: "Awutu Senya West", region: "Central" },
  { name: "Cape Coast", region: "Central" },
  { name: "Effutu", region: "Central" },
  { name: "Ekumfi", region: "Central" },
  { name: "Gomoa Central", region: "Central" },
  { name: "Gomoa East", region: "Central" },
  { name: "Gomoa West", region: "Central" },
  { name: "Komenda-Edina-Eguafo-Abirem", region: "Central" },
  { name: "Mfansteman", region: "Central" },
  { name: "Twifo-Atti-Morkwa", region: "Central" },
  { name: "Twifo-Hemang-Lower Denkyira", region: "Central" },
  { name: "Upper Denkyira East", region: "Central" },
  { name: "Upper Denkyira West", region: "Central" },
  { name: "Abuakwa North", region: "Eastern" },
  { name: "Abuakwa South", region: "Eastern" },
  { name: "Achiase", region: "Eastern" },
  { name: "Akuapem North", region: "Eastern" },
  { name: "Akuapem South", region: "Eastern" },
  { name: "Akyemansa", region: "Eastern" },
  { name: "Asene-Manso-Akroso", region: "Eastern" },
  { name: "Asuogyaman", region: "Eastern" },
  { name: "Atiwa East", region: "Eastern" },
  { name: "Atiwa West", region: "Eastern" },
  { name: "Ayensuano", region: "Eastern" },
  { name: "Birim Central", region: "Eastern" },
  { name: "Birim North", region: "Eastern" },
  { name: "Birim South", region: "Eastern" },
  { name: "Denkyembour", region: "Eastern" },
  { name: "Fanteakwa North", region: "Eastern" },
  { name: "Fanteakwa South", region: "Eastern" },
  { name: "Kwaebibirem", region: "Eastern" },
  { name: "Kwahu Afram Plains North", region: "Eastern" },
  { name: "Kwahu Afram Plains South", region: "Eastern" },
  { name: "Kwahu East", region: "Eastern" },
  { name: "Kwahu South", region: "Eastern" },
  { name: "Kwahu West", region: "Eastern" },
  { name: "Lower Manya-Krobo", region: "Eastern" },
  { name: "New Juaben North", region: "Eastern" },
  { name: "New Juaben South", region: "Eastern" },
  { name: "Nsawam Adoagyiri", region: "Eastern" },
  { name: "Okere", region: "Eastern" },
  { name: "Suhum", region: "Eastern" },
  { name: "Upper Manya", region: "Eastern" },
  { name: "Upper West Akim", region: "Eastern" },
  { name: "West Akim", region: "Eastern" },
  { name: "Yilo-Krobo", region: "Eastern" },
  { name: "Ablekuma Central", region: "Greater Accra" },
  { name: "Ablekuma North", region: "Greater Accra" },
  { name: "Ablekuma West", region: "Greater Accra" },
  { name: "Accra", region: "Greater Accra" },
  { name: "Ada East", region: "Greater Accra" },
  { name: "Ada West", region: "Greater Accra" },
  { name: "Adenta", region: "Greater Accra" },
  { name: "Ashaiman", region: "Greater Accra" },
  { name: "Ayawaso Central", region: "Greater Accra" },
  { name: "Ayawaso East", region: "Greater Accra" },
  { name: "Ayawaso North", region: "Greater Accra" },
  { name: "Ayawaso West", region: "Greater Accra" },
  { name: "Ga Central", region: "Greater Accra" },
  { name: "Ga East", region: "Greater Accra" },
  { name: "Ga North", region: "Greater Accra" },
  { name: "Ga South", region: "Greater Accra" },
  { name: "Korle-Klottey", region: "Greater Accra" },
  { name: "Kpone-Katamanso", region: "Greater Accra" },
  { name: "Krowor", region: "Greater Accra" },
  { name: "La-Dade-Kotopon", region: "Greater Accra" },
  { name: "La-Nkwantanang-Madina", region: "Greater Accra" },
  { name: "Ledzokuku", region: "Greater Accra" },
  { name: "Ningo-Prampram", region: "Greater Accra" },
  { name: "Okaikwei North", region: "Greater Accra" },
  { name: "Shai Osudoku", region: "Greater Accra" },
  { name: "Tema West", region: "Greater Accra" },
  { name: "Tema", region: "Greater Accra" },
  { name: "Weija Gbawe", region: "Greater Accra" },
  { name: "Biakoye", region: "Oti" },
  { name: "Jasikan", region: "Oti" },
  { name: "Kadjebi", region: "Oti" },
  { name: "Krachi East", region: "Oti" },
  { name: "Krachi Nchumuru", region: "Oti" },
  { name: "Krachi West", region: "Oti" },
  { name: "Nkwanta North", region: "Oti" },
  { name: "Nkwanta South", region: "Oti" },
  { name: "Guan", region: "Oti" },
  { name: "Adaklu", region: "Volta" },
  { name: "Afadzato South", region: "Volta" },
  { name: "Agotime Ziope", region: "Volta" },
  { name: "Akatsi North", region: "Volta" },
  { name: "Anloga", region: "Volta" },
  { name: "Central Tongu", region: "Volta" },
  { name: "Ho Municipal", region: "Volta" },
  { name: "Ho West", region: "Volta" },
  { name: "Keta Municipal", region: "Volta" },
  { name: "Ketu North", region: "Volta" },
  { name: "Ketu South", region: "Volta" },
  { name: "Kpando", region: "Volta" },
  { name: "North Dayi", region: "Volta" },
  { name: "North Tongi", region: "Volta" },
  { name: "South Dayi", region: "Volta" },
  { name: "South Tongu", region: "Volta" },
  { name: "Aowin", region: "Western North" },
  { name: "Bia East", region: "Western North" },
  { name: "Bia West", region: "Western North" },
  { name: "Bibiani-Anhwiaso-Bekwai", region: "Western North" },
  { name: "Bodi", region: "Western North" },
  { name: "Juaboso", region: "Western North" },
  { name: "Sefwi-Akontombra", region: "Western North" },
  { name: "Sefwi-Wiawso", region: "Western North" },
  { name: "Suaman", region: "Western North" },
  { name: "Ahantan West", region: "Western" },
  { name: "Effia Kwesimintsim", region: "Western" },
  { name: "Ellembelle", region: "Western" },
  { name: "Jomoro", region: "Western" },
  { name: "Mpohor", region: "Western" },
  { name: "Nzema East", region: "Western" },
  { name: "Prestea-Huni Valley", region: "Western" },
  { name: "Sekondi Takoradi", region: "Western" },
  { name: "Shama", region: "Western" },
  { name: "Tarkwa Nsuaem", region: "Western" },
  { name: "Wassa Amenfi Central", region: "Western" },
  { name: "Wassa Amenfi East", region: "Western" },
  { name: "Wassa Amenfi West", region: "Western" },
  { name: "Wassa East", region: "Western" },
];
